name: Keep Supabase Awake

on:
  schedule:
    - cron: '0 6 * * 1' # Every Monday at 06:00 UTC
  workflow_dispatch: # Optional: allow manual runs

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Send ping to Supabase
        run: |
          curl -sSf https://agicdzhhufcedtbsniuz.supabase.co/rest/v1/ --head || exit 1
